spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Temp1234
    url: jdbc:mysql://localhost:3306/olx-clients    #from olx-users to olx-clients
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect