server:
  port: 7000
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Temp1234
    url: jdbc:mysql://localhost:3306/securitydb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            
#spring.application.name=login-service
  application:
    name: login-service